#!/bin/bash

export JAVA_HOME=${JAVA_HOME:?JAVA_HOME must be set}
export PATH=$JAVA_HOME/bin:$PATH

rm -f mkmods.log
exec 2>mkmods.log
set -x
# to redirect anything to this log, just add 1>&3 to the end of the command

export TARGETDIR=${TARGETDIR:-target}
pushd ${TARGETDIR}

export DEPSIMGDIR=${DEPSIMGDIR:-deps-image}
export JMODSUBDIR=${JMODSUBDIR:-jmods}

printf "DEPSIMGDIR=${DEPSIMGDIR} JMODSUBDIR=${JMODSUBDIR} MODSDIR=${MODSDIR}\n"


#for file in $(find $DEPSIMGDIR -type f -name '*.jar')
if [ ! -d "${DEPSIMGDIR}" ]
then
 printf "deps dir 'DEPSIMGDIR' does not exist: %s\n" ${DEPSIMGDIR};
 exit 2
fi

printf "pwd:%s\n" $(pwd)

for file in $(find $DEPSIMGDIR -type f -name '*number-to-words*.jar')
do
 jarname=$(basename $file)
 modname=${jarname%%-[0-9.]*.jar}
 modname=${modname//-/.}

 printf "file:%s \n jarname:%s\n modname:%s\n" "${file}" "${jarname}" "${modname}"

 if unzip -l "${modulefile}" | grep 'module-info'
 then
  printf "FOUND MODULE-INFO...\n"
 else
  printf "NOT A MODULE\n"
   jdeps --multi-release 12 --module-path *.jar:${TARGETDIR}/${DEPSIMGDIR} --generate-module-info ${JMODSUBDIR} $file
   modulefile=${JMODSUBDIR}/${modname}/module-info.java
   if [ -f "${modulefile}" ]
   then
    printf " PRESENT\n"
    pushd ${JMODSUBDIR}/${modname}
     printf "PWD %s\n"  $(pwd)
     unzip ../../${file}
     javac module-info.java
#     jar uf ${modulefile} -C $ROOT_DIR/classes module-info.class
    popd
   else
    printf " MISSING\n"
   fi
 fi

done
exit 0

 if unzip -l $file | grep 'module-info'
 then
  printf "FOUND MODULE-INFO...\n"
 else
  printf "DID NOT FIND MODULE-INFO...\n"

  FN=$(basename $file)
  printf "FN: %s\n" ${FN}
  FN=${FN%%-[0-9.]*.jar}
  printf " FN: %s\n" ${FN}
  FN=${FN//-/.}
  printf "  FN: %s\n" ${FN}

  jdeps --multi-release 12 --module-path *.jar:dependencies --generate-module-info jmods $file
#  echo
#  pwd
#  (cd $MAINDIR/jmods/$FN && jar xf $MAINDIR/$file)
  
#  jar uf $file -C $ROOT_DIR/classes module-info.class
 fi
done

#jdeps --multi-release 12  --module-path ./*SNAPSHOT.jar:dependencies/ --generate-module-info out1 dependencies/jetty-io-9.4.18.v20190429.jar
